# Generated by Django 4.1.2 on 2022-10-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_completed_cart_is_active_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='tax',
            field=models.FloatField(default=2.25),
        ),
    ]
