# Generated by Django 4.1.2 on 2022-10-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitems_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
