# Generated by Django 4.1.2 on 2022-11-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_payment_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cart',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='orders',
        ),
    ]
