# Generated by Django 4.1.2 on 2022-10-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
