# Generated by Django 4.1.2 on 2022-10-31 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_created_on_customer_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_on',
        ),
    ]
