# Generated by Django 4.1.2 on 2022-11-03 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_brand_alter_cartitems_tax_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField()),
                ('status', models.IntegerField(choices=[('PENDING', 'pending'), ('FAILED', 'failed'), ('SUCCESS', 'success')], default=1)),
                ('cart_product', models.ManyToManyField(to='store.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
    ]
