# Generated by Django 4.1.2 on 2022-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_cart_payment_order_remove_payment_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.SmallIntegerField(choices=[('PENDING', 'pending'), ('FAILED', 'failed'), ('SUCCESS', 'success')], default=1),
        ),
    ]
