# Generated by Django 4.1.2 on 2022-11-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='tax',
        ),
    ]
