# Generated by Django 4.1.2 on 2022-11-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_productorder_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='tax',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
